import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import { Card, CardContent } from '@/Components/ui/card';
import { BrainCircuit, Lock, TrendingUp, TrendingDown, Target, AlertTriangle } from 'lucide-react';
import { Button } from '@/Components/ui/button';

export default function Signals({ auth, signals, history, free_limit, pro_limit }: any) {
    const isPro = auth.user.is_pro;
    const limit = isPro ? pro_limit : free_limit;
    
    // We already sliced the signals in backend, but we can visually show dummy locked ones if needed
    // However, backend only sends what they are allowed to see.
    // If they are free, let's show 1 "locked" card to tempt them.
    const showPaywall = !isPro && signals.length >= free_limit;

    return (
        <AuthenticatedLayout
            header={
                <div>
                    <h2 className="text-base md:text-2xl font-bold tracking-tight text-foreground flex items-center gap-2">
                        <BrainCircuit className="text-primary w-5 h-5 md:w-6 md:h-6" />
                        AI Trading Signals
                    </h2>
                    <p className="text-[10px] md:text-sm text-muted-foreground mt-1">
                        High-probability trade setups generated by Gemini AI. {isPro ? `You have ${pro_limit} daily signals.` : `Free tier limited to ${free_limit} daily signals.`}
                    </p>
                </div>
            }
        >
            <Head title="AI Signals" />

            <div className="py-4 md:py-8 space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {signals.map((sig: any) => (
                        <Card key={sig.id} className="bg-card border-border rounded-3xl overflow-hidden relative group">
                            <div className={`absolute top-0 right-0 p-4 ${sig.direction === 'long' ? 'text-emerald-500/10' : 'text-rose-500/10'}`}>
                                {sig.direction === 'long' ? <TrendingUp className="w-24 h-24 absolute -top-4 -right-4" /> : <TrendingDown className="w-24 h-24 absolute -top-4 -right-4" />}
                            </div>
                            
                            <CardContent className="p-6 relative z-10">
                                <div className="flex justify-between items-start mb-4">
                                    <div>
                                        <h3 className="text-2xl font-black tracking-tight">{sig.pair}</h3>
                                        <span className={`inline-block px-3 py-1 rounded-full text-xs font-bold mt-1 ${sig.direction === 'long' ? 'bg-emerald-500/20 text-emerald-500' : 'bg-rose-500/20 text-rose-500'}`}>
                                            {sig.direction.toUpperCase()}
                                        </span>
                                    </div>
                                    <span className="text-[10px] font-bold text-muted-foreground bg-secondary px-2 py-1 rounded-md">
                                        {new Date(sig.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                    </span>
                                </div>

                                <div className="space-y-4 mb-6">
                                    <div className="flex justify-between items-center border-b border-border/50 pb-2">
                                        <span className="text-xs text-muted-foreground font-medium">Entry</span>
                                        <span className="font-mono font-bold text-sm">{sig.entry_price}</span>
                                    </div>
                                    <div className="flex justify-between items-center border-b border-border/50 pb-2">
                                        <span className="text-xs text-muted-foreground font-medium flex items-center gap-1"><Target className="w-3 h-3 text-emerald-500"/> Take Profit</span>
                                        <span className="font-mono font-bold text-sm text-emerald-500">{sig.take_profit}</span>
                                    </div>
                                    <div className="flex justify-between items-center border-b border-border/50 pb-2">
                                        <span className="text-xs text-muted-foreground font-medium flex items-center gap-1"><AlertTriangle className="w-3 h-3 text-rose-500"/> Stop Loss</span>
                                        <span className="font-mono font-bold text-sm text-rose-500">{sig.stop_loss}</span>
                                    </div>
                                </div>

                                <div className="bg-secondary/50 rounded-xl p-3">
                                    <p className="text-[10px] leading-relaxed text-muted-foreground">
                                        <span className="font-bold text-foreground">AI Rationale:</span> {sig.reasoning}
                                    </p>
                                </div>
                            </CardContent>
                        </Card>
                    ))}

                    {/* Paywall Card */}
                    {showPaywall && (
                        <Card className="bg-card border-border rounded-3xl overflow-hidden relative flex flex-col items-center justify-center min-h-[300px] border-dashed border-primary/30 bg-primary/5">
                            <CardContent className="p-6 text-center z-10 flex flex-col items-center">
                                <div className="bg-background p-4 rounded-full shadow-2xl mb-4 border border-border">
                                    <Lock className="h-6 w-6 text-primary" />
                                </div>
                                <h3 className="text-lg font-bold text-foreground mb-2">Limit Reached</h3>
                                <p className="text-xs text-muted-foreground mb-6 max-w-[200px]">Upgrade to Pro to receive up to {pro_limit} high-probability signals per day.</p>
                                <Button 
                                    asChild
                                    size="sm"
                                    className="bg-primary hover:bg-primary/90 text-primary-foreground font-bold shadow-lg shadow-primary/20 rounded-full px-6"
                                >
                                    <Link href={route('profile.edit')}>Upgrade to Pro</Link>
                                </Button>
                            </CardContent>
                            <div className="absolute inset-0 bg-gradient-to-b from-transparent to-background/80 pointer-events-none" />
                        </Card>
                    )}

                    {signals.length === 0 && (
                        <div className="col-span-full py-12 text-center border-2 border-dashed border-border rounded-3xl">
                            <BrainCircuit className="w-12 h-12 text-muted-foreground/30 mx-auto mb-4" />
                            <h3 className="text-lg font-bold text-foreground">No Signals Yet</h3>
                            <p className="text-sm text-muted-foreground">The AI is currently analyzing the markets. Check back later.</p>
                        </div>
                    )}
                </div>

                {/* History Table */}
                <div className="mt-8">
                    <h3 className="text-lg font-bold text-foreground mb-4">Signal History</h3>
                    <div className="bg-card border-border rounded-3xl shadow-lg overflow-hidden">
                        <div className="overflow-x-auto no-scrollbar">
                            <table className="w-full text-sm text-left">
                                <thead className="text-[10px] uppercase text-muted-foreground bg-secondary/50 border-b border-border">
                                    <tr>
                                        <th className="px-4 py-3 font-medium">Date</th>
                                        <th className="px-4 py-3 font-medium">Pair</th>
                                        <th className="px-4 py-3 font-medium">Result</th>
                                        <th className="px-4 py-3 font-medium text-right">PnL</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {history.map((sig: any) => (
                                        <tr key={sig.id} className="border-b border-border/50">
                                            <td className="px-4 py-3 text-xs text-muted-foreground whitespace-nowrap">
                                                {new Date(sig.created_at).toLocaleDateString()}
                                            </td>
                                            <td className="px-4 py-3 font-bold">{sig.pair}</td>
                                            <td className="px-4 py-3">
                                                {sig.status === 'won' && <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/10 text-emerald-500">WON</span>}
                                                {sig.status === 'lost' && <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-500/10 text-rose-500">LOST</span>}
                                            </td>
                                            <td className={`px-4 py-3 text-right font-bold text-xs ${sig.pnl > 0 ? 'text-emerald-500' : (sig.pnl < 0 ? 'text-rose-500' : 'text-muted-foreground')}`}>
                                                {sig.pnl ? `${sig.pnl > 0 ? '+' : ''}${sig.pnl}` : '-'}
                                            </td>
                                        </tr>
                                    ))}
                                    {history.length === 0 && (
                                        <tr>
                                            <td colSpan={4} className="px-4 py-6 text-center text-muted-foreground text-xs">
                                                No historical data available.
                                            </td>
                                        </tr>
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
